// AUTO-GENERATED by almond-app/design/colors/generate_colorsets.py
// Do not edit by hand. Update tokens.json and re-run the script.

import SwiftUI

/// Type-safe accessors for the Almond color system.
/// Asset names are namespaced via `provides-namespace` in each group's Contents.json,
/// so the underlying asset paths are e.g. `base/Cocoa`, `roles/BrandPrimary`.
extension Color {
    // MARK: - Brand palette
    static let almondCreamBase = Color("base/CreamBase", bundle: .main)
    static let almondCreamTint = Color("base/CreamTint", bundle: .main)
    static let almondTan = Color("base/Tan", bundle: .main)
    static let almondCocoa = Color("base/Cocoa", bundle: .main)
    static let almondEspresso = Color("base/Espresso", bundle: .main)
    static let almondInk = Color("base/Ink", bundle: .main)

    // MARK: - Extended palette
    static let almondSage = Color("extended/Sage", bundle: .main)
    static let almondHoney = Color("extended/Honey", bundle: .main)
    static let almondCoral = Color("extended/Coral", bundle: .main)
    static let almondTerracotta = Color("extended/Terracotta", bundle: .main)
    static let almondSlate = Color("extended/Slate", bundle: .main)

    // MARK: - Semantic roles
    static let backgroundPrimary = Color("roles/BackgroundPrimary", bundle: .main)
    static let backgroundSecondary = Color("roles/BackgroundSecondary", bundle: .main)
    static let backgroundTertiary = Color("roles/BackgroundTertiary", bundle: .main)
    static let surfaceCard = Color("roles/SurfaceCard", bundle: .main)
    static let surfaceElevated = Color("roles/SurfaceElevated", bundle: .main)
    static let labelPrimary = Color("roles/LabelPrimary", bundle: .main)
    static let labelSecondary = Color("roles/LabelSecondary", bundle: .main)
    static let labelTertiary = Color("roles/LabelTertiary", bundle: .main)
    static let labelOnBrand = Color("roles/LabelOnBrand", bundle: .main)
    static let brandPrimary = Color("roles/BrandPrimary", bundle: .main)
    static let brandPrimaryStrong = Color("roles/BrandPrimaryStrong", bundle: .main)
    static let brandSecondary = Color("roles/BrandSecondary", bundle: .main)
    static let separator = Color("roles/Separator", bundle: .main)
    static let divider = Color("roles/Divider", bundle: .main)
    static let riskLow = Color("roles/RiskLow", bundle: .main)
    static let riskModerate = Color("roles/RiskModerate", bundle: .main)
    static let riskElevated = Color("roles/RiskElevated", bundle: .main)
    static let riskHigh = Color("roles/RiskHigh", bundle: .main)
    static let riskLowSurface = Color("roles/RiskLowSurface", bundle: .main)
    static let riskModerateSurface = Color("roles/RiskModerateSurface", bundle: .main)
    static let riskElevatedSurface = Color("roles/RiskElevatedSurface", bundle: .main)
    static let riskHighSurface = Color("roles/RiskHighSurface", bundle: .main)
    static let success = Color("roles/Success", bundle: .main)
    static let warning = Color("roles/Warning", bundle: .main)
    static let error = Color("roles/Error", bundle: .main)
    static let info = Color("roles/Info", bundle: .main)
    static let chartSeries1 = Color("roles/ChartSeries1", bundle: .main)
    static let chartSeries2 = Color("roles/ChartSeries2", bundle: .main)
    static let chartSeries3 = Color("roles/ChartSeries3", bundle: .main)
    static let chartSeries4 = Color("roles/ChartSeries4", bundle: .main)
    static let chartSeries5 = Color("roles/ChartSeries5", bundle: .main)

}
